# Generated by Django 5.1 on 2024-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messages_delete_for_all_messages_delete_for_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='delete_for_self',
            new_name='delete_for_author',
        ),
        migrations.AddField(
            model_name='messages',
            name='delete_for_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
