# Generated by Django 5.1 on 2024-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groups_admin_alter_groups_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
