# Generated by Django 5.1 on 2024-08-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_messages_receiver_remove_messages_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='delete_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='delete_for_self',
            field=models.BooleanField(default=False),
        ),
    ]
