# Generated by Django 5.1 on 2024-08-28 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_groups_user_groumembers_delete_groupmessages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrouMembers',
            new_name='GroupMembers',
        ),
    ]
