# Generated by Django 5.1 on 2024-08-20 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtoken_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 9, 44, 6, 801221, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
